#' @import sp
NULL

#' A convenience function to output the standard global S-value
#'
#' This function takes as input a spatial object generated by the \code{sppt} function
#' and returns the standard global S-value: the mean of all local \code{similarity}
#' values. The standard global S-value is the percentage of areas with a similar proportion
#' of test points as compared to the base points.
#'
#' @param sppt.sp  the spatialobject generated by the \code{sppt} function
#' @return         returns the standard global S-value
#' @examples
#' set.seed(76772)
#' myoutput <- sppt(base_points.sp = points1.sp, test_points.sp = points2.sp, uoa.sp = areas.sp)
#' summary.globalS.standard(myoutput)
#'
#' @keywords internal
summary.globalS.standard <- function(sppt.sp){
  mean(sppt.sp$globalS, na.rm=TRUE)
}


#' A convenience function to output the robust global S-value
#'
#' This function takes as input a spatial object generated by the \code{sppt} function
#' and returns the robust global S-value: the mean of all robust local \code{similarity}
#' values. The robust global S-value is the percentage of areas with a similar proportion
#' of test points as compared to the base points, not counting areas in which no points
#' occur in the base data and the test data.
#'
#' @param sppt.sp  the spatialobject generated by the \code{sppt} function
#' @return         returns the robust global S-value
#' @examples
#' set.seed(76772)
#' myoutput <- sppt(base_points.sp = points1.sp, test_points.sp = points2.sp, uoa.sp = areas.sp)
#' summary.globalS.robust(myoutput)
#'
#' @keywords internal
summary.globalS.robust <- function(sppt.sp){
  mean(sppt.sp$globalS.robust, na.rm=TRUE)
}


#' A convenience function to output S-values
#'
#' This function takes as input a spatial object generated by the \code{sppt} function
#' and returns the standard global S-value and the robust global S-value in a list. The standard
#' global S-value refers to the mean of all local \code{similarity} values (i.e.,
#' the percentage of areas with a similar proportion of test points as compared to the base points.)
#' The robust global S-value refers to the mean of all robust local \code{similarity}
#' values. The robust global S-value is the percentage of areas with a similar proportion
#' of test points as compared to the base points, not counting areas in which no points
#' occur in both the base data and the test data.
#'
#' @param sppt.sp  the spatialobject generated by the \code{sppt} function
#' @return         returns the standard and robust global S-values
#' @examples
#' set.seed(76772)
#' myoutput <- sppt(base_points.sp = points1.sp, test_points.sp = points2.sp, uoa.sp = areas.sp)
#' summary.sppt(myoutput)
#'
#' @export
summary.sppt <- function(sppt.sp){
  return(list(globalS.standard = summary.globalS.standard(sppt.sp),
              globalS.robust = summary.globalS.robust(sppt.sp)
              )
         )
}
